/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedAdminWatchLiveRouteImport } from './routes/_authenticated/admin.watch-live'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin.transactions'
import { Route as AuthenticatedAdminTopTeamsRouteImport } from './routes/_authenticated/admin.top-teams'
import { Route as AuthenticatedAdminTopLeaguesRouteImport } from './routes/_authenticated/admin.top-leagues'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminStripeWebhooksRouteImport } from './routes/_authenticated/admin.stripe-webhooks'
import { Route as AuthenticatedAdminRatingsRouteImport } from './routes/_authenticated/admin.ratings'
import { Route as AuthenticatedAdminNotificationRouteImport } from './routes/_authenticated/admin.notification'
import { Route as AuthenticatedAdminLiveMatchesRouteImport } from './routes/_authenticated/admin.live-matches'
import { Route as AuthenticatedAdminInsightsRouteImport } from './routes/_authenticated/admin.insights'
import { Route as AuthenticatedAdminHotMatchesRouteImport } from './routes/_authenticated/admin.hot-matches'
import { Route as AuthenticatedAdminClientQueryRouteImport } from './routes/_authenticated/admin.client-query'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminWatchLiveRoute =
  AuthenticatedAdminWatchLiveRouteImport.update({
    id: '/watch-live',
    path: '/watch-live',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTopTeamsRoute =
  AuthenticatedAdminTopTeamsRouteImport.update({
    id: '/top-teams',
    path: '/top-teams',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTopLeaguesRoute =
  AuthenticatedAdminTopLeaguesRouteImport.update({
    id: '/top-leagues',
    path: '/top-leagues',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStripeWebhooksRoute =
  AuthenticatedAdminStripeWebhooksRouteImport.update({
    id: '/stripe-webhooks',
    path: '/stripe-webhooks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRatingsRoute =
  AuthenticatedAdminRatingsRouteImport.update({
    id: '/ratings',
    path: '/ratings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationRoute =
  AuthenticatedAdminNotificationRouteImport.update({
    id: '/notification',
    path: '/notification',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLiveMatchesRoute =
  AuthenticatedAdminLiveMatchesRouteImport.update({
    id: '/live-matches',
    path: '/live-matches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInsightsRoute =
  AuthenticatedAdminInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHotMatchesRoute =
  AuthenticatedAdminHotMatchesRouteImport.update({
    id: '/hot-matches',
    path: '/hot-matches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientQueryRoute =
  AuthenticatedAdminClientQueryRouteImport.update({
    id: '/client-query',
    path: '/client-query',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/leagues': typeof LeaguesRoute
  '/pricing': typeof PricingRoute
  '/schedule': typeof ScheduleRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/live': typeof AuthenticatedLiveRoute
  '/match/$id': typeof MatchIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/client-query': typeof AuthenticatedAdminClientQueryRoute
  '/admin/hot-matches': typeof AuthenticatedAdminHotMatchesRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/admin/live-matches': typeof AuthenticatedAdminLiveMatchesRoute
  '/admin/notification': typeof AuthenticatedAdminNotificationRoute
  '/admin/ratings': typeof AuthenticatedAdminRatingsRoute
  '/admin/stripe-webhooks': typeof AuthenticatedAdminStripeWebhooksRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/top-leagues': typeof AuthenticatedAdminTopLeaguesRoute
  '/admin/top-teams': typeof AuthenticatedAdminTopTeamsRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/watch-live': typeof AuthenticatedAdminWatchLiveRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/leagues': typeof LeaguesRoute
  '/pricing': typeof PricingRoute
  '/schedule': typeof ScheduleRoute
  '/live': typeof AuthenticatedLiveRoute
  '/match/$id': typeof MatchIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/client-query': typeof AuthenticatedAdminClientQueryRoute
  '/admin/hot-matches': typeof AuthenticatedAdminHotMatchesRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/admin/live-matches': typeof AuthenticatedAdminLiveMatchesRoute
  '/admin/notification': typeof AuthenticatedAdminNotificationRoute
  '/admin/ratings': typeof AuthenticatedAdminRatingsRoute
  '/admin/stripe-webhooks': typeof AuthenticatedAdminStripeWebhooksRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/top-leagues': typeof AuthenticatedAdminTopLeaguesRoute
  '/admin/top-teams': typeof AuthenticatedAdminTopTeamsRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/watch-live': typeof AuthenticatedAdminWatchLiveRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/leagues': typeof LeaguesRoute
  '/pricing': typeof PricingRoute
  '/schedule': typeof ScheduleRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/match/$id': typeof MatchIdRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/client-query': typeof AuthenticatedAdminClientQueryRoute
  '/_authenticated/admin/hot-matches': typeof AuthenticatedAdminHotMatchesRoute
  '/_authenticated/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/_authenticated/admin/live-matches': typeof AuthenticatedAdminLiveMatchesRoute
  '/_authenticated/admin/notification': typeof AuthenticatedAdminNotificationRoute
  '/_authenticated/admin/ratings': typeof AuthenticatedAdminRatingsRoute
  '/_authenticated/admin/stripe-webhooks': typeof AuthenticatedAdminStripeWebhooksRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/top-leagues': typeof AuthenticatedAdminTopLeaguesRoute
  '/_authenticated/admin/top-teams': typeof AuthenticatedAdminTopTeamsRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/watch-live': typeof AuthenticatedAdminWatchLiveRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/leagues'
    | '/pricing'
    | '/schedule'
    | '/admin'
    | '/live'
    | '/match/$id'
    | '/admin/analytics'
    | '/admin/client-query'
    | '/admin/hot-matches'
    | '/admin/insights'
    | '/admin/live-matches'
    | '/admin/notification'
    | '/admin/ratings'
    | '/admin/stripe-webhooks'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/top-leagues'
    | '/admin/top-teams'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/watch-live'
    | '/api/public/stripe-webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/leagues'
    | '/pricing'
    | '/schedule'
    | '/live'
    | '/match/$id'
    | '/admin/analytics'
    | '/admin/client-query'
    | '/admin/hot-matches'
    | '/admin/insights'
    | '/admin/live-matches'
    | '/admin/notification'
    | '/admin/ratings'
    | '/admin/stripe-webhooks'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/top-leagues'
    | '/admin/top-teams'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/watch-live'
    | '/api/public/stripe-webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/leagues'
    | '/pricing'
    | '/schedule'
    | '/_authenticated/admin'
    | '/_authenticated/live'
    | '/match/$id'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/client-query'
    | '/_authenticated/admin/hot-matches'
    | '/_authenticated/admin/insights'
    | '/_authenticated/admin/live-matches'
    | '/_authenticated/admin/notification'
    | '/_authenticated/admin/ratings'
    | '/_authenticated/admin/stripe-webhooks'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/top-leagues'
    | '/_authenticated/admin/top-teams'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/watch-live'
    | '/api/public/stripe-webhook'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  LeaguesRoute: typeof LeaguesRoute
  PricingRoute: typeof PricingRoute
  ScheduleRoute: typeof ScheduleRoute
  MatchIdRoute: typeof MatchIdRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/watch-live': {
      id: '/_authenticated/admin/watch-live'
      path: '/watch-live'
      fullPath: '/admin/watch-live'
      preLoaderRoute: typeof AuthenticatedAdminWatchLiveRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/top-teams': {
      id: '/_authenticated/admin/top-teams'
      path: '/top-teams'
      fullPath: '/admin/top-teams'
      preLoaderRoute: typeof AuthenticatedAdminTopTeamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/top-leagues': {
      id: '/_authenticated/admin/top-leagues'
      path: '/top-leagues'
      fullPath: '/admin/top-leagues'
      preLoaderRoute: typeof AuthenticatedAdminTopLeaguesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stripe-webhooks': {
      id: '/_authenticated/admin/stripe-webhooks'
      path: '/stripe-webhooks'
      fullPath: '/admin/stripe-webhooks'
      preLoaderRoute: typeof AuthenticatedAdminStripeWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ratings': {
      id: '/_authenticated/admin/ratings'
      path: '/ratings'
      fullPath: '/admin/ratings'
      preLoaderRoute: typeof AuthenticatedAdminRatingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notification': {
      id: '/_authenticated/admin/notification'
      path: '/notification'
      fullPath: '/admin/notification'
      preLoaderRoute: typeof AuthenticatedAdminNotificationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/live-matches': {
      id: '/_authenticated/admin/live-matches'
      path: '/live-matches'
      fullPath: '/admin/live-matches'
      preLoaderRoute: typeof AuthenticatedAdminLiveMatchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/insights': {
      id: '/_authenticated/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AuthenticatedAdminInsightsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hot-matches': {
      id: '/_authenticated/admin/hot-matches'
      path: '/hot-matches'
      fullPath: '/admin/hot-matches'
      preLoaderRoute: typeof AuthenticatedAdminHotMatchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/client-query': {
      id: '/_authenticated/admin/client-query'
      path: '/client-query'
      fullPath: '/admin/client-query'
      preLoaderRoute: typeof AuthenticatedAdminClientQueryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminClientQueryRoute: typeof AuthenticatedAdminClientQueryRoute
  AuthenticatedAdminHotMatchesRoute: typeof AuthenticatedAdminHotMatchesRoute
  AuthenticatedAdminInsightsRoute: typeof AuthenticatedAdminInsightsRoute
  AuthenticatedAdminLiveMatchesRoute: typeof AuthenticatedAdminLiveMatchesRoute
  AuthenticatedAdminNotificationRoute: typeof AuthenticatedAdminNotificationRoute
  AuthenticatedAdminRatingsRoute: typeof AuthenticatedAdminRatingsRoute
  AuthenticatedAdminStripeWebhooksRoute: typeof AuthenticatedAdminStripeWebhooksRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTopLeaguesRoute: typeof AuthenticatedAdminTopLeaguesRoute
  AuthenticatedAdminTopTeamsRoute: typeof AuthenticatedAdminTopTeamsRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWatchLiveRoute: typeof AuthenticatedAdminWatchLiveRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminClientQueryRoute: AuthenticatedAdminClientQueryRoute,
  AuthenticatedAdminHotMatchesRoute: AuthenticatedAdminHotMatchesRoute,
  AuthenticatedAdminInsightsRoute: AuthenticatedAdminInsightsRoute,
  AuthenticatedAdminLiveMatchesRoute: AuthenticatedAdminLiveMatchesRoute,
  AuthenticatedAdminNotificationRoute: AuthenticatedAdminNotificationRoute,
  AuthenticatedAdminRatingsRoute: AuthenticatedAdminRatingsRoute,
  AuthenticatedAdminStripeWebhooksRoute: AuthenticatedAdminStripeWebhooksRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminTopLeaguesRoute: AuthenticatedAdminTopLeaguesRoute,
  AuthenticatedAdminTopTeamsRoute: AuthenticatedAdminTopTeamsRoute,
  AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWatchLiveRoute: AuthenticatedAdminWatchLiveRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  LeaguesRoute: LeaguesRoute,
  PricingRoute: PricingRoute,
  ScheduleRoute: ScheduleRoute,
  MatchIdRoute: MatchIdRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
